appName: devteambot
appVersion: v1.0.0
environment: ${ENVIRONMENT:development}
shutdownDelay: 10 # in seconds

http:
  port: ${HTTP_PORT:9050}
  writeTimeout: 30 # in seconds
  readTimeout: 30 # in seconds

logger:
  fileLocation: logs/devteambot.log
  fileMaxSize: ${LOG_FILE_MAX_SIZE:20} # megabytes
  fileMaxBackup: ${LOG_FILE_MAX_BACKUP:10}
  fileMaxAge: ${LOG_FILE_MAX_AGE:30} # days
  stdout: ${LOG_STDOUT:true}

database:
  host: ${DB_HOST:127.0.0.1}
  port: ${DB_PORT:5432}
  dbName: ${DB_NAME:devteambot}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  sslmode: ${DB_SSLMODE:disable}
  maxIdleConn: ${DB_MAX_IDLE_CONN:10}
  connMaxLifetime: ${DB_CONN_MAX_LIFETIME:1} # in hours
  maxOpenConn: ${DB_MAX_OPEN_CONN:100}

discord:
  appID: ${DISCORD_APP_ID}
  token: ${DISCORD_TOKEN}

redis:
  address: ${REDIS_ADDRESS:127.0.0.1}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD}

googleai:
  token: ${GOOGLE_AI_TOKEN}

n8n:
  baseURL: https://n8n.tommynurwantoro.com
  username: ${N8N_USERNAME}
  password: ${N8N_PASSWORD}
  webhookID: ${N8N_WEBHOOK_ID}

schedulers:
  - sholat-get-today-schedule:
      enable: true
      time:
        hour: 3
        minute: 0
        second: 0
  - sholat-send-reminder:
      enable: true
  - presensi-send-reminder-pagi:
      enable: true
      time:
        hour: 7
        minute: 55
        second: 0
  - presensi-send-reminder-sore:
      enable: true
      time:
        hour: 17
        minute: 5
        second: 0
  - point-reset-quota:
      enable: true
      time:
        hour: 0
        minute: 0
        second: 0
